name: flutter_form
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Seatify
      fonts:
        - asset: assets/fonts/superchargegrad.ttf